# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app:rw
      - profuel_db:/app/instance
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: "${SECRET_KEY}"
      SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  profuel_db:
