services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    # Ejecuta ambos comandos en un shell para que el "&&" funcione
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0"
