"""training + overview

Revision ID: 0132cf0c11d2
Revises: f0fb2fcec7ff
Create Date: 2025-08-14 17:28:24.040502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0132cf0c11d2'
down_revision = 'f0fb2fcec7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_actuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_actuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_actuals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_actuals_user_id'), ['user_id'], unique=False)

    op.create_table('training_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_training_intent_user_date')
    )
    with op.batch_alter_table('training_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_intents_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_intents_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_intents_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_intents_date'))

    op.drop_table('training_intents')
    with op.batch_alter_table('training_actuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_actuals_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_actuals_date'))

    op.drop_table('training_actuals')
    # ### end Alembic commands ###
