"""training models aligned (intent + actual)

Revision ID: 0725448e1955
Revises: 0132cf0c11d2
Create Date: 2025-08-15 16:16:50.554089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0725448e1955'
down_revision = '0132cf0c11d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_actuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('distance_m', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('elevation_m', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_power_w', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_hr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.String(length=5), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=24),
               nullable=False)
        batch_op.drop_column('start_at')
        batch_op.drop_column('source')
        batch_op.drop_column('end_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('kcal')

    with op.batch_alter_table('training_intents', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=24),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_training_intent_user_date'), type_='unique')
        batch_op.create_unique_constraint('uq_training_intents_user_date', ['user_id', 'date'])
        batch_op.drop_column('source')
        batch_op.drop_column('confidence')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_intents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=16), nullable=False))
        batch_op.drop_constraint('uq_training_intents_user_date', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_training_intent_user_date'), ['user_id', 'date'])
        batch_op.alter_column('type',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('training_actuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kcal', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('start_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('started_at')
        batch_op.drop_column('avg_hr')
        batch_op.drop_column('avg_power_w')
        batch_op.drop_column('elevation_m')
        batch_op.drop_column('distance_m')
        batch_op.drop_column('duration_min')

    # ### end Alembic commands ###
