"""add base_meal_slots + slot_alternatives

Revision ID: 945d55a05a33
Revises: f06c6867b015
Create Date: 2025-08-13 09:10:00.004237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945d55a05a33'
down_revision = 'f06c6867b015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_meal_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_meal_id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sa.String(length=64), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('serving_qty', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('cho_g', sa.Float(), nullable=False),
    sa.Column('pro_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['base_meal_id'], ['base_meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('serving_qty', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('cho_g', sa.Float(), nullable=False),
    sa.Column('pro_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['base_meal_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_alternatives')
    op.drop_table('base_meal_slots')
    # ### end Alembic commands ###
