"""profile goals/distribution/tolerances/training_mods

Revision ID: d23ce32fee16
Revises: d75ca992f456
Create Date: 2025-08-10 21:39:30.550214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd23ce32fee16'
down_revision = 'd75ca992f456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_goals', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True))
        batch_op.add_column(sa.Column('meal_plan', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True))
        batch_op.add_column(sa.Column('training_mods', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('training_mods')
        batch_op.drop_column('meal_plan')
        batch_op.drop_column('daily_goals')

    # ### end Alembic commands ###
