"""init

Revision ID: d75ca992f456
Revises: 9f55284da8a8
Create Date: 2025-08-10 17:15:25.936757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75ca992f456'
down_revision = '9f55284da8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_per_100g', sa.Float(), nullable=True),
    sa.Column('kcal_per_unit', sa.Float(), nullable=True),
    sa.Column('protein_per_unit', sa.Float(), nullable=True),
    sa.Column('carbs_per_unit', sa.Float(), nullable=True),
    sa.Column('fat_per_unit', sa.Float(), nullable=True),
    sa.Column('default_unit', sa.String(length=20), nullable=False),
    sa.Column('default_quantity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('fats', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_meal_quantity_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('actividad', sa.Float(), nullable=False),
    sa.Column('formula_bmr', sa.String(length=20), nullable=False),
    sa.Column('porcentaje_grasa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('meals')
    op.drop_table('user')
    op.drop_table('foods')
    # ### end Alembic commands ###
