"""base meals + diary apply

Revision ID: f06c6867b015
Revises: e647b83bc5e2
Create Date: 2025-08-13 08:39:16.918531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06c6867b015'
down_revision = 'e647b83bc5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('total_kcal', sa.Float(), nullable=False),
    sa.Column('total_cho_g', sa.Float(), nullable=False),
    sa.Column('total_pro_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meal_type', name='uq_base_meal_user_mealtype')
    )
    with op.batch_alter_table('base_meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_meals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_meals_user_id'))

    op.drop_table('base_meals')
    # ### end Alembic commands ###
