"""diary models

Revision ID: f0fb2fcec7ff
Revises: 945d55a05a33
Create Date: 2025-08-14 16:14:55.937155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fb2fcec7ff'
down_revision = '945d55a05a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_diary_day_user_date')
    )
    with op.batch_alter_table('diary_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_days_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diary_days_user_id'), ['user_id'], unique=False)

    op.create_table('diary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('slot_name', sa.String(length=64), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('serving_qty', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('cho_g', sa.Float(), nullable=False),
    sa.Column('pro_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['diary_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diary_items_meal_type'), ['meal_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_items_meal_type'))

    op.drop_table('diary_items')
    with op.batch_alter_table('diary_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diary_days_user_id'))
        batch_op.drop_index(batch_op.f('ix_diary_days_date'))

    op.drop_table('diary_days')
    # ### end Alembic commands ###
