name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SQLALCHEMY_DATABASE_URI: 'sqlite:///:memory:'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pip-audit black flake8

      - name: Check formatting with Black
        run: black --check .

      - name: Lint with flake8
        run: flake8 --max-line-length=88 .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Security audit
        run: pip-audit --fail-on high
