# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Usar SQLite en memoria para los tests de SQLAlchemy
      SQLALCHEMY_DATABASE_URI: 'sqlite:///:memory:'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pip-audit flake8

      - name: Lint with flake8
        # Ignoramos trailing whitespace (W291) y line breaks before binario (W503)
        run: flake8 --max-line-length=88 --ignore=W291,W503 .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Security audit
        # No bloquear el pipeline por vulnerabilidades; revisar manualmente
        run: pip-audit || true
